/*
 * To change this template, choose Tools // Templates
 * and open the template in the editor.
 */


import Métier.Fournisseur;
import dao.BddDAO;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.YES_NO_OPTION;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JTextField;

/**
 *
 * @author btssio
 */
public class JFrameFournisseurs extends javax.swing.JFrame{

    DefaultTableModel model = new DefaultTableModel(); 
    boolean modif = false;
    JComboBox comboBoxFourni;
    JTextField fieldCores;
    JTextField fieldTel;
    JTextField fieldFax;
    JTextField fieldMail;
    
    /**
     * Creates new form JFrameDemoModeleList
     */
    public JFrameFournisseurs(JComboBox comboBoxFourni, JTextField fieldCores,  JTextField fieldTel, JTextField fieldFax, JTextField fieldMail) {
        initComponents();
        this.pack();
        this.setLocationRelativeTo(null);
        this.setVisible(true);
        this.comboBoxFourni=comboBoxFourni;
        this.fieldCores=fieldCores;
        this.fieldTel=fieldTel;
        this.fieldFax=fieldFax;
        this.fieldMail=fieldMail;
        String[] colums = {"Libelle","Correspondant","Tel","Fax","Mail"};
        model.setColumnIdentifiers(colums);     
        this.tabFourni.setModel(model);
        tabFourni.getColumnModel().getColumn(0).setPreferredWidth(200);
        tabFourni.getColumnModel().getColumn(1).setPreferredWidth(150);
        tabFourni.getColumnModel().getColumn(2).setPreferredWidth(110);
        tabFourni.getColumnModel().getColumn(3).setPreferredWidth(110);
        tabFourni.getColumnModel().getColumn(4).setPreferredWidth(230);
        try{
            String fournisseursString = BddDAO.importFournisseursFromText();
            String[] fournisseursString2 = fournisseursString.split("//");
            Arrays.sort(fournisseursString2);
            for(int i=0;i<fournisseursString2.length;i++){
                String[] fournisseurString = fournisseursString2[i].split(";");
                String libelle="";
                String correspondant="";
                String tel="";
                String fax="";
                String mail="";
                try{
                    libelle=fournisseurString[0];
                    correspondant=fournisseurString[1];
                    tel=fournisseurString[2];
                    fax=fournisseurString[3];
                    mail=fournisseurString[4];
                }catch(Exception e){
                    
                }
                Fournisseur unFournisseur = new Fournisseur(libelle, correspondant, tel, fax, mail);
                model.addRow(new Object[]{unFournisseur.getLibelle(),unFournisseur.getCorrespondant(),unFournisseur.getTel(),unFournisseur.getFax(),unFournisseur.getMail()});
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Un problème est survenu au chargement de la BDD", "Erreur", JOptionPane.ERROR_MESSAGE);
        }
    }

    public static JTable getjTable2() {
        return tabFourni;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField6 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabFourni = new javax.swing.JTable();
        boutonAjoutFourni = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        boutonValider = new javax.swing.JButton();
        fieldRechercher = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();

        jMenu1.setText("File");
        jMenuBar2.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar2.add(jMenu2);

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("FOURNISSEURS");
        setIconImage(new ImageIcon("./image/logo-sol2s.png" ).getImage());
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tabFourni.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tabFourni.setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        tabFourni.getTableHeader().setReorderingAllowed(false);
        tabFourni.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tabFourniPropertyChange(evt);
            }
        });
        tabFourni.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tabFourniKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(tabFourni);
        tabFourni.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);

        boutonAjoutFourni.setText("+");
        boutonAjoutFourni.setToolTipText("Ajouter un fournisseur");
        boutonAjoutFourni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonAjoutFourniActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel1.setText("Fournisseurs");

        boutonValider.setText("Valider");
        boutonValider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonValiderActionPerformed(evt);
            }
        });

        fieldRechercher.setText("Rechercher");
        fieldRechercher.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                fieldRechercherCaretUpdate(evt);
            }
        });
        fieldRechercher.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fieldRechercherFocusGained(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(boutonAjoutFourni)
                        .addGap(313, 313, 313)
                        .addComponent(jLabel1)
                        .addGap(155, 155, 155)
                        .addComponent(fieldRechercher, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(377, 377, 377)
                .addComponent(boutonValider)
                .addGap(378, 378, 378))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(fieldRechercher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(boutonAjoutFourni)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(boutonValider)
                .addContainerGap())
        );

        jMenu3.setText("Aide");
        jMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu3MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boutonAjoutFourniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonAjoutFourniActionPerformed
        // TODO add your handling code here:
        new JFrameAjoutFournisseur(comboBoxFourni,fieldCores,fieldTel,fieldFax,fieldMail).setVisible(true);
    }//GEN-LAST:event_boutonAjoutFourniActionPerformed

    private void tabFourniKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tabFourniKeyPressed
        // TODO add your handling code here:
        if(tabFourni.getSelectedRow()!=-1){
            int keyCode = evt.getKeyCode(); 
            if (keyCode == KeyEvent.VK_DELETE) {
                int reply = JOptionPane.showConfirmDialog(null, "Etes vous sûr de vouloir supprimer cet élément ?", "", YES_NO_OPTION);
                if (reply == JOptionPane.YES_OPTION){
                    int index = tabFourni.getSelectedRow();
                    DefaultTableModel model = (DefaultTableModel) tabFourni.getModel();
                    Object fourniSuppr = model.getValueAt(index, 0);
                    comboBoxFourni.removeItem(fourniSuppr);
                    comboBoxFourni.setSelectedIndex(0);
                    model.removeRow(index);

                    ArrayList forunisseurs = new ArrayList();
                    for(int i=0;i<this.tabFourni.getRowCount();i++){
                        String libelle = (String)this.tabFourni.getValueAt(i,0);
                        String correspondant = (String)this.tabFourni.getValueAt(i,1);
                        String tel = (String)this.tabFourni.getValueAt(i,2);
                        String fax = (String)this.tabFourni.getValueAt(i,3);
                        String mail = (String)this.tabFourni.getValueAt(i,4);
                        Fournisseur unFournisseur = new Fournisseur(libelle,correspondant,tel,fax,mail);
                        String unFournisseurString = unFournisseur.getLibelle()+";"+unFournisseur.getCorrespondant()+";"+unFournisseur.getTel()+";"+unFournisseur.getFax()+";"+unFournisseur.getMail()+";//";
                        forunisseurs.add(unFournisseurString);
                    }
                    BddDAO.exportFournisseurToText(forunisseurs);
                }
            } 
        }else{
            JOptionPane.showMessageDialog(null, "Veuillez sélectionner une ligne", "Erreur", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_tabFourniKeyPressed

    private void tabFourniPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tabFourniPropertyChange
        // TODO add your handling code here:
        modif=true;
    }//GEN-LAST:event_tabFourniPropertyChange

    private void boutonValiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonValiderActionPerformed
        // TODO add your handling code here:
        if(this.tabFourni.getSelectedRow()!=-1){ 
            ArrayList fournisseurs = new ArrayList();
            for(int i=0;i<this.tabFourni.getRowCount();i++){
                String libelle = (String)this.tabFourni.getValueAt(i,0);
                String correspondant = (String)this.tabFourni.getValueAt(i,1);
                String tel = (String)this.tabFourni.getValueAt(i,2);
                String fax = (String)this.tabFourni.getValueAt(i,3);
                String mail = (String)this.tabFourni.getValueAt(i,4);
                Fournisseur unFournisseur = new Fournisseur(libelle,correspondant,tel,fax,mail);
                String unFournisseurString = unFournisseur.getLibelle()+";"+unFournisseur.getCorrespondant()+";"+unFournisseur.getTel()+";"+unFournisseur.getFax()+";"+unFournisseur.getMail()+";//";
                fournisseurs.add(unFournisseurString);
            }
            BddDAO.exportFournisseurToText(fournisseurs);
            Object valueCell = tabFourni.getValueAt(tabFourni.getSelectedRow(), 0);
            comboBoxFourni.setSelectedItem(valueCell);
        }
        JOptionPane.showMessageDialog(this, "Modifications effectuées", "Info", JOptionPane.INFORMATION_MESSAGE);
        this.dispose();
    }//GEN-LAST:event_boutonValiderActionPerformed

    private void jMenu3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu3MouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Pour supprimer : Séletionner une ligne puis appuyer sur la touche suppr\n"
                + "Pour modifier : double clic sur une cellule du tableau\n"
                + "Pour ajouter : cliquer sur le bouton +",
                "Infos", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jMenu3MouseClicked

    private void fieldRechercherCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_fieldRechercherCaretUpdate
        // TODO add your handling code here:
        int rowCount = this.tabFourni.getRowCount();
        for (int i=rowCount-1 ; i>=0 ; --i) model.removeRow(i);

        try{
            String fournisseursString = BddDAO.importFournisseursFromText();
            String[] fournisseursString2 = fournisseursString.split("//");
            Arrays.sort(fournisseursString2);
            for(int i=0;i<fournisseursString2.length;i++){
                String[] fournisseurString = fournisseursString2[i].split(";");
                String libelle="";
                String correspondant="";
                String tel="";
                String fax="";
                String mail="";
                try{
                    libelle=fournisseurString[0];
                    correspondant=fournisseurString[1];
                    tel=fournisseurString[2];
                    fax=fournisseurString[3];
                    mail=fournisseurString[4];
                }catch(Exception e){
                    
                }
                Fournisseur unFournisseur = new Fournisseur(libelle, correspondant, tel, fax, mail);
                if(unFournisseur.getLibelle().contains(fieldRechercher.getText()) || unFournisseur.getLibelle().contains(fieldRechercher.getText().toUpperCase())){
                    model.addRow(new Object[]{unFournisseur.getLibelle(),unFournisseur.getCorrespondant(),unFournisseur.getTel(),unFournisseur.getFax(),unFournisseur.getMail()});
                }
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Un problème est survenu au chargement de la BDD", "Erreur", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_fieldRechercherCaretUpdate

    private void fieldRechercherFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldRechercherFocusGained
        // TODO add your handling code here:
        fieldRechercher.setText("");
    }//GEN-LAST:event_fieldRechercherFocusGained

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        if(modif == false){
            this.dispose();
        }else{
            JOptionPane jop = new JOptionPane();			
            int option = jop.showConfirmDialog(null, "Voulez-vous enregistrer les modifications avant de quitter ?", "Enregistrer ?", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if(option == JOptionPane.OK_OPTION){
                if(this.tabFourni.getSelectedRow()!=-1){ 
                    ArrayList fournisseurs = new ArrayList();
                    for(int i=0;i<this.tabFourni.getRowCount();i++){
                        String libelle = (String)this.tabFourni.getValueAt(i,0);
                        String correspondant = (String)this.tabFourni.getValueAt(i,1);
                        String tel = (String)this.tabFourni.getValueAt(i,2);
                        String fax = (String)this.tabFourni.getValueAt(i,3);
                        String mail = (String)this.tabFourni.getValueAt(i,4);
                        Fournisseur unFournisseur = new Fournisseur(libelle,correspondant,tel,fax,mail);
                        String unFournisseurString = unFournisseur.getLibelle()+";"+unFournisseur.getCorrespondant()+";"+unFournisseur.getTel()+";"+unFournisseur.getFax()+";"+unFournisseur.getMail()+";//";
                        fournisseurs.add(unFournisseurString);
                    }
                    BddDAO.exportFournisseurToText(fournisseurs);
                    Object valueCell = tabFourni.getValueAt(tabFourni.getSelectedRow(), 0);
                    comboBoxFourni.setSelectedItem(valueCell);
                }
                JOptionPane.showMessageDialog(this, "Modifications effectuées", "Info", JOptionPane.INFORMATION_MESSAGE);
                this.dispose();
            }else{
                if(option == JOptionPane.NO_OPTION){
                    this.dispose();
                }
            }
        }
    }//GEN-LAST:event_formWindowClosing

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boutonAjoutFourni;
    private javax.swing.JButton boutonValider;
    private javax.swing.JTextField fieldRechercher;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField9;
    private static javax.swing.JTable tabFourni;
    // End of variables declaration//GEN-END:variables
}
