/*
 * To change this template, choose Tools // Templates
 * and open the template in the editor.
 */


import Métier.Fournisseur;
import DAO.BddDAO;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author btssio
 */
public class JFrameAjoutFournisseur extends javax.swing.JFrame {

    DefaultTableModel model = new DefaultTableModel(); 
    JComboBox comboBoxFourniRecup;
    JTextField fieldCorresRecup;
    JTextField fieldTelRecup;
    JTextField fieldFaxRecup;
    JTextField fieldMailRecup;
    
    /**
     * Creates new form JFrameDemoModeleList
     * @param comboBoxFourniRecup
     * @param fieldCorresRecup
     * @param fieldTelRecup
     * @param fieldFaxRecup
     * @param fieldMailRecup
     */
    public JFrameAjoutFournisseur(JComboBox comboBoxFourniRecup, JTextField fieldCorresRecup,  JTextField fieldTelRecup, JTextField fieldFaxRecup, JTextField fieldMailRecup) {
        initComponents();
        this.pack();
        this.setLocationRelativeTo(null);
        this.setVisible(true);
        this.comboBoxFourniRecup=comboBoxFourniRecup;
        this.fieldCorresRecup=fieldCorresRecup;
        this.fieldTelRecup=fieldTelRecup;
        this.fieldFaxRecup=fieldFaxRecup;
        this.fieldMailRecup=fieldMailRecup;
    }
    
    public static Fournisseur getFournisseur(){
        String correspondant = JFrameAjoutFournisseur.fieldCorres.getText();
        String libelle = JFrameAjoutFournisseur.fieldDesti.getText();
        String tel = JFrameAjoutFournisseur.fieldTel.getText();
        String fax = JFrameAjoutFournisseur.fieldFax.getText();
        String mail = JFrameAjoutFournisseur.fieldMail.getText();

        Fournisseur fournisseurAjout = new Fournisseur(libelle,correspondant,tel,fax,mail);
        return fournisseurAjout;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField6 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        fieldTel = new javax.swing.JTextField();
        boutonValider = new javax.swing.JButton();
        fieldMail = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        fieldCorres = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        fieldFax = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        fieldDesti = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("AJOUT FOURNISSEUR");
        setIconImage(new ImageIcon("./image/logo-sol2s.png" ).getImage());
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        boutonValider.setText("Valider");
        boutonValider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonValiderActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel6.setText("Ajouter Fournisseur");

        jLabel4.setText("Tel :");

        jLabel1.setText("Destinataire :");

        jLabel3.setText("Correspondant :");

        jLabel2.setText("Mail :");

        jLabel5.setText("Fax :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(boutonValider)
                        .addGap(106, 106, 106))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(fieldTel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(fieldDesti, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(fieldFax, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(fieldMail, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fieldCorres, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jLabel6)
                .addGap(80, 80, 80))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(fieldDesti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(fieldCorres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(fieldTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(fieldFax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(fieldMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(boutonValider)
                .addContainerGap())
        );

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boutonValiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonValiderActionPerformed
        // TODO add your handling code here:
        boolean actualiser=true;
        try{
            String correspondant = JFrameAjoutFournisseur.fieldCorres.getText();
            String libelle = JFrameAjoutFournisseur.fieldDesti.getText();
            String tel = JFrameAjoutFournisseur.fieldTel.getText();
            String fax = JFrameAjoutFournisseur.fieldFax.getText();
            String mail = JFrameAjoutFournisseur.fieldMail.getText();
            
            Fournisseur fournisseurAjout = new Fournisseur(libelle,correspondant,tel,fax,mail);
            model = (DefaultTableModel) JFrameFournisseurs.getjTable2().getModel();
            model.addRow(new Object[]{fournisseurAjout.getLibelle(),fournisseurAjout.getCorrespondant(),fournisseurAjout.getTel(),fournisseurAjout.getFax(),fournisseurAjout.getMail()});
            
            String s =  System.getProperty("line.separator");
            String fournisseurAjoutString = s+fournisseurAjout.getLibelle()+";"+fournisseurAjout.getCorrespondant()+";"+fournisseurAjout.getTel()+";"+fournisseurAjout.getFax()+";"+fournisseurAjout.getMail()+";//";
            String fournisseursString = BddDAO.importFournisseursFromText();
            String lesFournisseurs = fournisseursString+fournisseurAjoutString;

            ArrayList fournisseurs = new ArrayList();
            fournisseurs.add(lesFournisseurs);
            
            BddDAO.exportFournisseurToText(fournisseurs);
            
            Fournisseur unFournisseur = getFournisseur();
            for(int i=0;i<comboBoxFourniRecup.getItemCount();i++){
                if(comboBoxFourniRecup.getItemAt(i).equals(unFournisseur.getLibelle())){
                    actualiser=false;
                }
            } 
            if(actualiser){
                comboBoxFourniRecup.addItem(unFournisseur.getLibelle());
                comboBoxFourniRecup.setSelectedItem(unFournisseur.getLibelle());
                fieldCorresRecup.setText(unFournisseur.getCorrespondant());
                fieldTelRecup.setText(unFournisseur.getTel());
                fieldFaxRecup.setText(unFournisseur.getFax());  
                fieldMailRecup.setText(unFournisseur.getMail());
            }
            
            JOptionPane.showMessageDialog(null, "Le Fournisseur a été ajouté", "Info", JOptionPane.INFORMATION_MESSAGE);
            
            this.dispose();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Un problème est survenu", "Erreur", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_boutonValiderActionPerformed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boutonValider;
    private static javax.swing.JTextField fieldCorres;
    private static javax.swing.JTextField fieldDesti;
    private static javax.swing.JTextField fieldFax;
    private static javax.swing.JTextField fieldMail;
    private static javax.swing.JTextField fieldTel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
