/*
 * To change this template, choose Tools // Templates
 * and open the template in the editor.
 */


import Métier.Client;
import javax.swing.JFrame;
import dao.BddDAO;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author btssio
 */
public class JFrameAjoutClient extends javax.swing.JFrame {

    DefaultTableModel model = new DefaultTableModel(); 
    
    /**
     * Creates new form JFrameDemoModeleList
     */
    public JFrameAjoutClient() {
        initComponents();
        this.pack();
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }
    
    public static Client getClient(){
        String libelle = JFrameAjoutClient.fieldEntreprise.getText();
        String correspondant = JFrameAjoutClient.fieldCorres.getText();
        String tel = JFrameAjoutClient.fieldTel.getText();
        String fax = JFrameAjoutClient.fieldFax.getText();
        String mail = JFrameAjoutClient.fieldMail.getText();
        String adresse = JFrameAjoutClient.fieldAdresse.getText();

        Client clientAjout = new Client(libelle,correspondant,tel,fax,mail,adresse);
        return clientAjout;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField6 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        fieldCorres = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        fieldTel = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        fieldAdresse = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        boutonValider = new javax.swing.JButton();
        fieldEntreprise = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        fieldMail = new javax.swing.JTextField();
        fieldFax = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("AJOUT CLIENT");
        setIconImage(new ImageIcon("./image/logo-sol2s.png" ).getImage());
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setText("Tel :");

        jLabel6.setText("Entreprise :");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel7.setText("Ajouter un Client");

        jLabel3.setText("Fax :");

        jLabel5.setText("Adresse :");

        boutonValider.setText("Valider");
        boutonValider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonValiderActionPerformed(evt);
            }
        });

        jLabel4.setText("Mail :");

        jLabel1.setText("Correspondant :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel6)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fieldEntreprise)
                            .addComponent(fieldAdresse)
                            .addComponent(fieldMail)
                            .addComponent(fieldCorres)
                            .addComponent(fieldTel)
                            .addComponent(fieldFax))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(boutonValider)
                        .addGap(155, 155, 155))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addComponent(jLabel7)
                .addGap(128, 128, 128))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(fieldEntreprise, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(fieldCorres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(fieldTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldFax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldAdresse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addComponent(boutonValider)
                .addContainerGap())
        );

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boutonValiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonValiderActionPerformed
        // TODO add your handling code here:
        boolean actualiser=true;
        try{
            String libelle = JFrameAjoutClient.fieldEntreprise.getText();
            String correspondant = JFrameAjoutClient.fieldCorres.getText();
            String tel = JFrameAjoutClient.fieldTel.getText();
            String fax = JFrameAjoutClient.fieldFax.getText();
            String mail = JFrameAjoutClient.fieldMail.getText();
            String adresse = JFrameAjoutClient.fieldAdresse.getText();

            Client clientAjout = new Client(libelle,correspondant,tel,fax,mail,adresse);
            model = (DefaultTableModel) JFrameClients.getjTable2().getModel();
            model.addRow(new Object[]{clientAjout.getLibelle(),clientAjout.getCorrespondant(),clientAjout.getTel(),clientAjout.getFax(),clientAjout.getMail(),clientAjout.getAdresse()});
            
            String s =  System.getProperty("line.separator");
            String clientAjoutString = s+clientAjout.getLibelle()+";"+clientAjout.getCorrespondant()+";"+clientAjout.getTel()+";"+clientAjout.getFax()+";"+clientAjout.getMail()+";"+clientAjout.getAdresse()+";//";
            String clientsString = BddDAO.importClientsFromText();
            String lesClients = clientsString+clientAjoutString;

            ArrayList clients = new ArrayList();
            clients.add(lesClients);
            
            BddDAO.exportClientToText(clients);

            Client unClient = getClient();
            for(int i=0;i<JFrameDevisGest.getjComboBox5().getItemCount();i++){
                if(JFrameDevisGest.getjComboBox5().getItemAt(i).equals(unClient.getLibelle())){
                    actualiser=false;
                }
            } 
            if(actualiser){
                JFrameDevisGest.getjComboBox5().addItem(unClient.getLibelle());
                JFrameDevisGest.getjComboBox5().setSelectedItem(unClient.getLibelle());
                JFrameDevisGest.getjTextField5().setText(unClient.getCorrespondant());
                JFrameDevisGest.getjTextField1().setText(unClient.getTel());
                JFrameDevisGest.getjTextField2().setText(unClient.getFax());  
                JFrameDevisGest.getjTextField4().setText(unClient.getMail());
                JFrameDevisGest.getjTextField6().setText(unClient.getAdresse());
            }
            
            JOptionPane.showMessageDialog(null, "Le client a été ajouté", "Info", JOptionPane.INFORMATION_MESSAGE);
            
            this.dispose();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Un problème est survenu", "Erreur", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_boutonValiderActionPerformed

    public String getDestinataire() 
    { 
        String destinataire = this.fieldTel.getText(); 
        return destinataire; 
    } 

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boutonValider;
    private static javax.swing.JTextField fieldAdresse;
    private static javax.swing.JTextField fieldCorres;
    private static javax.swing.JTextField fieldEntreprise;
    private static javax.swing.JTextField fieldFax;
    private static javax.swing.JTextField fieldMail;
    private static javax.swing.JTextField fieldTel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
