/*
 * To change this template, choose Tools // Templates
 * and open the template in the editor.
 */


import Métier.Produit;
import DAO.BddDAO;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.YES_NO_OPTION;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author btssio
 */
public class JFrameProduits extends javax.swing.JFrame {

    DefaultTableModel model = new DefaultTableModel(); 
    boolean modif = false;
    
    /**
     * Creates new form JFrameDemoModeleList
     */
    public JFrameProduits() {
        initComponents();
        this.pack();
        this.setLocationRelativeTo(null);
        this.setVisible(true);
        String[] colums = {"Ref","Unité"};
        model.setColumnIdentifiers(colums);     
        JFrameProduits.tabProd.setModel(model);
        tabProd.getColumnModel().getColumn(0).setPreferredWidth(300);
        try{
            String produitsString = BddDAO.importProduitsFromText();
            String[] produitsString2 = produitsString.split("//");
            Arrays.sort(produitsString2);
            for (String produitsString21 : produitsString2) {
                String[] produitString = produitsString21.split(";");
                String ref="";
                String unite="";
                try{
                    ref=produitString[0];
                    unite=produitString[1];
                }catch(Exception e){
                    
                }
                Produit unProduit = new Produit(ref, unite);
                model.addRow(new Object[]{unProduit.getRef(),unProduit.getUnite()});
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Un problème est survenu au chargement de la BDD", "Erreur", JOptionPane.ERROR_MESSAGE);
        }
    }

    public static JTable getjTable2() {
        return tabProd;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField6 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabProd = new javax.swing.JTable();
        boutonAjoutProd = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        boutonValider = new javax.swing.JButton();
        boutonRechercher = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("PRODUITS");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tabProd.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ref", "Unité"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tabProd.setColumnSelectionAllowed(true);
        tabProd.setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        tabProd.getTableHeader().setReorderingAllowed(false);
        tabProd.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tabProdPropertyChange(evt);
            }
        });
        tabProd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tabProdKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(tabProd);
        tabProd.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        if (tabProd.getColumnModel().getColumnCount() > 0) {
            tabProd.getColumnModel().getColumn(0).setPreferredWidth(300);
        }

        boutonAjoutProd.setText("+");
        boutonAjoutProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonAjoutProdActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel1.setText("Produits");

        boutonValider.setText("Valider");
        boutonValider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonValiderActionPerformed(evt);
            }
        });

        boutonRechercher.setText("Rechercher");
        boutonRechercher.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                boutonRechercherCaretUpdate(evt);
            }
        });
        boutonRechercher.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                boutonRechercherFocusGained(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(boutonAjoutProd)
                        .addGap(157, 157, 157)
                        .addComponent(jLabel1)
                        .addGap(46, 46, 46)
                        .addComponent(boutonRechercher, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(205, 205, 205)
                .addComponent(boutonValider)
                .addGap(204, 204, 204))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(boutonAjoutProd)
                    .addComponent(boutonRechercher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(boutonValider)
                .addContainerGap())
        );

        jMenu1.setText("Aide");
        jMenu1.setToolTipText("Ajouter un produit");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boutonAjoutProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonAjoutProdActionPerformed
        // TODO add your handling code here:
        new JFrameAjoutProduit().setVisible(true);
    }//GEN-LAST:event_boutonAjoutProdActionPerformed

    private void tabProdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tabProdKeyPressed
        // TODO add your handling code here:
        int keyCode = evt.getKeyCode(); 
        if (keyCode == KeyEvent.VK_DELETE) {
            int reply = JOptionPane.showConfirmDialog(null, "Etes vous sûr de vouloir supprimer cet élément ?", "", YES_NO_OPTION);
            if (reply == JOptionPane.YES_OPTION){
                int index = tabProd.getSelectedRow();
                DefaultTableModel tableModel = (DefaultTableModel) tabProd.getModel();
                tableModel.removeRow(index);

                ArrayList produits = new ArrayList();
                for(int i=0;i<JFrameProduits.tabProd.getRowCount();i++){
                    String ref = (String)JFrameProduits.tabProd.getValueAt(i,0);
                    String unite = (String)JFrameProduits.tabProd.getValueAt(i,1);
                    Produit unProduit = new Produit(ref,unite);
                    String unProduitString = unProduit.getRef()+";"+unProduit.getUnite()+";//";
                    produits.add(unProduitString);
                }
                BddDAO.exportProduitToText(produits);
            }
        } 
    }//GEN-LAST:event_tabProdKeyPressed

    private void tabProdPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tabProdPropertyChange
        // TODO add your handling code here:
        modif=true;
    }//GEN-LAST:event_tabProdPropertyChange

    private void boutonValiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonValiderActionPerformed
        // TODO add your handling code here:
        if(JFrameProduits.tabProd.getSelectedRow()!=-1){
            ArrayList produits = new ArrayList();
            for(int i=0;i<JFrameProduits.tabProd.getRowCount();i++){
                String ref = (String)JFrameProduits.tabProd.getValueAt(i,0);
                String unite = (String)JFrameProduits.tabProd.getValueAt(i,1);
                Produit unProduit = new Produit(ref,unite);
                String unProduitString = unProduit.getRef()+";"+unProduit.getUnite()+";//";
                produits.add(unProduitString);
            }
            BddDAO.exportProduitToText(produits);
        }
        JOptionPane.showMessageDialog(this, "Modifications effectuées", "Info", JOptionPane.INFORMATION_MESSAGE);
        this.dispose();
    }//GEN-LAST:event_boutonValiderActionPerformed

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Pour supprimer : S\u00e9letionner une ligne puis appuyer sur la touche suppr\n"
                + "Pour modifier : double clic sur une cellule du tableau\n"
                + "Pour ajouter : cliquer sur le bouton +",
                "Infos", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jMenu1MouseClicked

    private void boutonRechercherCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_boutonRechercherCaretUpdate
        // TODO add your handling code here:
        int rowCount = JFrameProduits.tabProd.getRowCount();
        for (int i=rowCount-1 ; i>=0 ; --i) model.removeRow(i);

        try{
            String produitsString = BddDAO.importProduitsFromText();
            String[] produitsString2 = produitsString.split("//");
            Arrays.sort(produitsString2);
            for (String produitsString21 : produitsString2) {
                String[] produitString = produitsString21.split(";");
                String ref="";
                String unite="";
                try{
                    ref=produitString[0];
                    unite=produitString[1];
                }catch(Exception e){
                    
                }
                Produit unProduit = new Produit(ref, unite);
                if(unProduit.getRef().contains(boutonRechercher.getText()) || unProduit.getRef().contains(boutonRechercher.getText().toUpperCase())){
                    model.addRow(new Object[]{unProduit.getRef(),unProduit.getUnite()});
                }
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Un problème est survenu au chargement de la BDD", "Erreur", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_boutonRechercherCaretUpdate

    private void boutonRechercherFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_boutonRechercherFocusGained
        // TODO add your handling code here:
        boutonRechercher.setText("");
    }//GEN-LAST:event_boutonRechercherFocusGained

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        if(modif == false){
            this.dispose();
        }else{
            int option = JOptionPane.showConfirmDialog(null, "Voulez-vous enregistrer les modifications avant de quitter ?", "Enregistrer ?", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if(option == JOptionPane.OK_OPTION){
                if(JFrameProduits.tabProd.getSelectedRow()!=-1){
                    ArrayList produits = new ArrayList();
                    for(int i=0;i<JFrameProduits.tabProd.getRowCount();i++){
                        String ref = (String)JFrameProduits.tabProd.getValueAt(i,0);
                        String unite = (String)JFrameProduits.tabProd.getValueAt(i,1);
                        Produit unProduit = new Produit(ref,unite);
                        String unProduitString = unProduit.getRef()+";"+unProduit.getUnite()+";//";
                        produits.add(unProduitString);
                    }
                    BddDAO.exportProduitToText(produits);
                }
                JOptionPane.showMessageDialog(this, "Modifications effectuées", "Info", JOptionPane.INFORMATION_MESSAGE);
                this.dispose();
            }else{
                if(option == JOptionPane.NO_OPTION){
                    this.dispose();
                }
            }
        }
    }//GEN-LAST:event_formWindowClosing

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boutonAjoutProd;
    private javax.swing.JTextField boutonRechercher;
    private javax.swing.JButton boutonValider;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField9;
    private static javax.swing.JTable tabProd;
    // End of variables declaration//GEN-END:variables
}
